---
- name: Jinja2 default filters
  hosts: localhost
  gather_facts: False
  vars:
        prime_numbers: [1, 2, 5, 7, 11, 13, 17, 19, 23, 29]
  tasks:

    # If interface is not defined, the integer value of 45 will be used
    # rather than raising an error. Pausing a playbook is sometimes necessary
    # in networking plays to prevent racing.
    - name: Jinja2 default filter - example
      pause:
        seconds: "{{ sleeptime | default(45) }}"

    - name: Random prime number
      debug:
        msg: "Show me a randon prime number: '{{ prime_numbers|random }}'"

    # If you want to use the default value when vars evaluate to false or an empty string
    # then you have to set a second parameter to true
    - name: Jinja2 default filter - example
      debug:
        msg: "Prevent undefined var err {{ myvariable | default('by setting a default', true) }}"

